apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: argo-repo
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: master
  url: https://github.com/argoproj/argo-rollouts
