apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: todoproject-namespace
spec:
  chart:
    spec:
      chart: nats
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nats
  interval: 1m0s
