apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: todoproject
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/vheinamaki/devops-with-kubernetes
  ref:
    branch: main
