apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todoproject
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: todoproject
  interval: 10m
  path: ./part4/e08/manifests
  prune: true
  validation: client
